# This is a basic workflow to help you get started with Actions

name: Deploy to Raspberry Pi

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Setup 
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
          cache: 'npm'          
      - name: Install dependencies
        run: npm ci
      - name: Build Typescript
        run: npm run build
      
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Debug SSH connection
        run: |
          echo "SSH key: ${SSH_PRIVATE_KEY}"
          echo "Host: ${SSH_HOST}"
          echo "Username: ${SSH_USERNAME}"
          echo "Port: ${SSH_PORT}"
          echo "Command: ${SSH_SCRIPT}"
          echo "Running SSH command..."
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PI_SSH_KEY }}
          SSH_HOST: ${{ secrets.PI_HOST }}
          SSH_USERNAME: ${{ secrets.PI_USERNAME }}
          SSH_PORT: ${{ secrets.PI_PORT }}
          SSH_SCRIPT: "npm start"  # Adjust this if needed

      - name: Debug SSH private key
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Copy artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist
      
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./dist
      
      - name: Deploy to miniserver
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USERNAME }}
          port: ${{ secrets.PI_PORT }}
          script: |
            npm start